export const orders = [
  {
    id: 1,
    customer: "Lütfullah ÇELENK",
    date: "30.07.2022",
    cost: 87,
    detail: "Tamamlanmış Sipariş",
    note: "Lütfen kapıyı çalmayınız.",
    address: "Koşuyolu Mh. Mahmut Yesari Cad. No:8 34718 Kadıköy/İstanbul",
    content: [
      { order: "1 Mercimek Çorbası" },
      { order: "1 porsiyon Adana Dürüm" },
      { order: "1 adet Kola" },
      { order: "1 porsyion Künefe" },
    ],
  },
  {
    id: 2,
    customer: "Ali ÇELİK",
    date: "30.07.2022",
    cost: 64,
    detail: "Tamamlanmış Sipariş",
    note: "Lütfen kapıyı çalmayınız.",
    address: "Koşuyolu Mh. Mahmut Yesari Cad. No:8 34718 Kadıköy/İstanbul",
    content: [
      { order: "1 Mercimek Çorbası" },
      { order: "1 porsiyon Adana Dürüm" },
      { order: "1 adet Kola" },
      { order: "1 porsyion Künefe" },
    ],
  },
  {
    id: 3,
    customer: "Sefa SEZEN",
    date: "30.07.2022",
    cost: 56,
    detail: "Yolda Olan Sipariş",
    note: "Lütfen kapıyı çalmayınız.",
    address: "Koşuyolu Mh. Mahmut Yesari Cad. No:8 34718 Kadıköy/İstanbul",
    content: [
      { order: "1 Mercimek Çorbası" },
      { order: "1 porsiyon Adana Dürüm" },
      { order: "1 adet Kola" },
      { order: "1 porsyion Künefe" },
    ],
  },
  {
    id: 4,
    customer: "Yağız TÜRK",
    date: "30.07.2022",
    cost: 78,
    detail: "Yeni Sipariş",
    note: "Lütfen kapıyı çalmayınız.",
    address: "Koşuyolu Mh. Mahmut Yesari Cad. No:8 34718 Kadıköy/İstanbul",
    content: [
      { order: "1 Mercimek Çorbası" },
      { order: "1 porsiyon Adana Dürüm" },
      { order: "1 adet Kola" },
      { order: "1 porsyion Künefe" },
    ],
  },
  {
    id: 5,
    customer: "Veli DEMİR",
    date: "30.07.2022",
    cost: 102,
    detail: "Tamamlanmış Sipariş",
    note: "Lütfen kapıyı çalmayınız.",
    address: "Koşuyolu Mh. Mahmut Yesari Cad. No:8 34718 Kadıköy/İstanbul",
    content: [
      { order: "1 Mercimek Çorbası" },
      { order: "1 porsiyon Adana Dürüm" },
      { order: "1 adet Kola" },
      { order: "1 porsyion Künefe" },
    ],
  },
  {
    id: 6,
    customer: "Burak KALIN",
    date: "30.07.2022",
    cost: 56,
    detail: "Tamamlanmış Sipariş",
    note: "Lütfen kapıyı çalmayınız.",
    address: "Koşuyolu Mh. Mahmut Yesari Cad. No:8 34718 Kadıköy/İstanbul",
    content: [
      { order: "1 Mercimek Çorbası" },
      { order: "1 porsiyon Adana Dürüm" },
      { order: "1 adet Kola" },
      { order: "1 porsyion Künefe" },
    ],
  },
  {
    id: 7,
    customer: "Hande DENİZ",
    date: "30.07.2022",
    cost: 55,
    detail: "Yeni Sipariş",
    note: "Lütfen kapıyı çalmayınız.",
    address: "Koşuyolu Mh. Mahmut Yesari Cad. No:8 34718 Kadıköy/İstanbul",
    content: [
      { order: "1 Mercimek Çorbası" },
      { order: "1 porsiyon Adana Dürüm" },
      { order: "1 adet Kola" },
      { order: "1 porsyion Künefe" },
    ],
  },

  {
    id: 8,
    customer: "Kartal BAKIR",
    date: "30.07.2022",
    cost: 82,
    detail: "Yolda Olan Sipariş",
    note: "Lütfen kapıyı çalmayınız.",
    address: "Koşuyolu Mh. Mahmut Yesari Cad. No:8 34718 Kadıköy/İstanbul",
    content: [
      { order: "1 Mercimek Çorbası" },
      { order: "1 porsiyon Adana Dürüm" },
      { order: "1 adet Kola" },
      { order: "1 porsyion Künefe" },
    ],
  },

  {
    id: 9,
    customer: "Berk CİRDİ",
    date: "30.07.2022",
    cost: 45,
    detail: "Yolda Olan Sipariş",
    note: "Lütfen kapıyı çalmayınız.",
    address: "Koşuyolu Mh. Mahmut Yesari Cad. No:8 34718 Kadıköy/İstanbul",
    content: [
      { order: "1 Mercimek Çorbası" },
      { order: "1 porsiyon Adana Dürüm" },
      { order: "1 adet Kola" },
      { order: "1 porsyion Künefe" },
    ],
  },
  {
    id: 10,
    customer: "Melisa CAN",
    date: "30.07.2022",
    cost: 66,
    detail: "Yeni Sipariş",
    note: "Lütfen kapıyı çalmayınız.",
    address: "Koşuyolu Mh. Mahmut Yesari Cad. No:8 34718 Kadıköy/İstanbul",
    content: [
      { order: "1 Mercimek Çorbası" },
      { order: "1 porsiyon Adana Dürüm" },
      { order: "1 adet Kola" },
      { order: "1 porsyion Künefe" },
    ],
  },
  {
    id: 11,
    customer: "Seray YAZI",
    date: "30.07.2022",
    cost: 70,
    detail: "Yolda Olan Sipariş",
    note: "Lütfen kapıyı çalmayınız.",
    address: "Koşuyolu Mh. Mahmut Yesari Cad. No:8 34718 Kadıköy/İstanbul",
    content: [
      { order: "1 Mercimek Çorbası" },
      { order: "1 porsiyon Adana Dürüm" },
      { order: "1 adet Kola" },
      { order: "1 porsyion Künefe" },
    ],
  },
  {
    id: 12,
    customer: "Aslı UZUN",
    date: "30.07.2022",
    cost: 52,
    detail: "Yeni Sipariş",
    note: "Lütfen kapıyı çalmayınız.",
    address: "Koşuyolu Mh. Mahmut Yesari Cad. No:8 34718 Kadıköy/İstanbul",
    content: [
      { order: "1 Mercimek Çorbası" },
      { order: "1 porsiyon Adana Dürüm" },
      { order: "1 adet Kola" },
      { order: "1 porsyion Künefe" },
    ],
  },
];
